name: Run Shell Script with User Question

on:
  workflow_dispatch:
    inputs:
      load_time:
        description: "Enter Load Time"
        required: true
        type: string
      deploy_type:
        description: "Enter Deploy Type"
        required: true
        type: string
      user_question:
        description: "Enter your question"
        required: true
        type: string

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Ensures script exists

      - name: Make script executable
        run: chmod +x script.sh  # Ensures script has execute permissions

      - name: Run Shell Script with User Input
        run: ./script.sh "${{ inputs.load_time }}" "${{ inputs.deploy_type }}" "${{ inputs.user_question }}"
