# This is a basic workflow to help you get started with Actions

name: OPEA ChatQnA deployment - Docker
run-name: Deploy OPEA ChatQnA on ${{github.event.inputs.RUNNER_NAME}} in ${{github.event.inputs.DEPLOY_TYPE}} mode / Model ${{github.event.inputs.MODEL}} / ${{ github.event.inputs.LOAD_MODEL_TIME_LIMIT }}s

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      DEPLOY_TYPE:
        description: 'choose cpu or gpu'
        required: true
        default: 'cpu'
        type: choice
        options:
          - 'cpu'
          - 'gpu'
      LOAD_MODEL_TIME_LIMIT:
        description: 'Load model time limit'
        required: true
        default: '1000'
        type: number
      QUESTION:
        description: 'Question or Query'
        required: true
        default: 'What is the revenue of Nike in 2023?'
jobs:
  validate_services:
    runs-on: ubuntu-latest
    steps:
      - name: Validate ChatQnA service
        run: |
          chmod +x validate.sh
          bash ./validate.sh ${{ github.event.inputs.LOAD_MODEL_TIME_LIMIT }}  ${{ github.event.inputs.DEPLOY_TYPE }} ${{ github.event.inputs.QUESTION }} 
